proxy_cache_path /www/wwwroot/buqin.com.cn/proxy_cache_dir levels=1:2 keys_zone=buqin_com_cn_cache:20m inactive=1d max_size=5g;
server {
    listen 80;
    server_name buqin.com.cn www.buqin.com.cn 152.136.161.179;
    root /www/wwwroot/buyuan-company-website;
    #CERT-APPLY-CHECK--START
    # 用于SSL证书申请时的文件验证相关配置 -- 请勿删除
    include /www/server/panel/vhost/nginx/well-known/buqin.com.cn.conf;
    #CERT-APPLY-CHECK--END

    # 引入用户自定义扩展配置文件，请勿删除
    include /www/server/panel/vhost/nginx/extension/buqin.com.cn/*.conf;
    index index.html;
    location /ai/api/tables/ { # ununsed
        proxy_pass http://127.0.0.1:8086/api/tables/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /ai/ {
        proxy_pass http://127.0.0.1:8085/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        client_max_body_size 20m;
    }

    location /schedule-api/ {
        proxy_pass http://127.0.0.1:3002/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 20m;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3002;
        proxy_bind $server_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/buqin.com.cn.conf;
    #REWRITE-END

    location / {
        try_files $uri $uri/ =404;
    }
    access_log /var/log/nginx/buqin_access.log;
    error_log /var/log/nginx/buqin_error.log;
    listen 443 ssl; # managed by Certbot
    # SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    ssl_certificate /etc/letsencrypt/live/buqin.com.cn/fullchain.pem; # managed by Certbot
    #SSL-END

    ssl_certificate_key /etc/letsencrypt/live/buqin.com.cn/privkey.pem; # managed by Certbot
    # This file contains important security parameters. If you modify this file

    # manually, Certbot will be unable to automatically provide future security

    # updates. Instead, Certbot will print and log an error message with a path to

    # the up-to-date file that you will need to refer to when manually updating

    # this file. Contents are based on https://ssl-config.mozilla.org
    ssl_session_cache shared:le_nginx_SSL:10m;
    ssl_session_timeout 1440m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.buqin.com.cn) {
        return 301 https://$host$request_uri;
    }
    # managed by Certbot
    if ($host = buqin.com.cn) {
        return 301 https://$host$request_uri;
    }
    # managed by Certbot
    listen 80;
    server_name buqin.com.cn www.buqin.com.cn 152.136.161.179;
    return 404; # managed by Certbot
}